---
title: ""
author: "Youngsoo Baek, YunranChen and Xiaojun Zheng"
date: "1/20/2020"
output: 
  ioslides_presentation:
    widescreen: true
    smaller: true
---

<style>
slides > slide {
  overflow-x: auto !important;
  overflow-y: auto !important;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(arm)
library(ggplot2)
library(dplyr)
library(MASS)
library(ggpubr)
library(monomvn)
library(BAS)
library(R2jags)
library(ggmosaic)
```

## EDA

```{r EDA}
Longnecker <- readRDS("./Longnecker.rds")
Longnecker <- Longnecker[,colnames(Longnecker)!="albumin"] # Throw away albumin
Longnecker$center <- as.factor(Longnecker$center) # Factorize center
Longnecker[Longnecker$gestational_age > 46, "gestational_age"] <- 46 # Truncate at age == 46
data = Longnecker
data_age_na<- data[-which(is.na(data$pcb_028)), ]

ggplot(data = data_age_na) +
   geom_mosaic(aes(x = product(race, center), fill=race), na.rm=TRUE)+
  labs(x = "Center ID", y = "Race", title='Race by center')
```

## Challenges

  * Noisy measurement
  
  * Multicollinearity
  
  * Modeling Heterogeneity between centers

## Regression estimates

```{r, echo=F, include=T}
# Boilerplate
Longnecker <- readRDS("./Longnecker.rds")
Longnecker <- Longnecker[,colnames(Longnecker)!="albumin"] # Throw away albumin
Longnecker$center <- as.factor(Longnecker$center) # Factorize center
Longnecker[Longnecker$gestational_age > 46, "gestational_age"] <- 46 # Truncate at age == 46
x <- model.matrix(gestational_age ~ . - center, data = Longnecker)
miss_indices <- as.integer(row.names(x))
Longnecker_complete <- Longnecker[miss_indices,] # Only those non-missing obs.
PC1_pcb <- prcomp(x[,grepl("pcb", colnames(x))])$x[,1]
Longnecker_complete_pc <- cbind.data.frame(
  Longnecker_complete[,!grepl("pcb", colnames(Longnecker_complete))],
  PC1 = PC1_pcb)
lm_with_pc <- lm(gestational_age ~ ., data = Longnecker_complete_pc)
Longnecker_complete_pc$early <- (Longnecker_complete_pc$gestational_age < 37)
llm_with_pc <- glm(early ~ . - gestational_age, family = binomial, data = Longnecker_complete_pc)
lm_coefs <- c( coef(lm_with_pc)[c("dde", "PC1")],
   "center5" = as.numeric(coef(lm_with_pc)[1]),
   coef(lm_with_pc)[1] + coef(lm_with_pc)[ grepl("center", names(coef(lm_with_pc))) ] )
lm_confint <- rbind(confint(lm_with_pc)[c("dde", "PC1"),],
                    "center5" = confint(lm_with_pc)[1,],
                    confint(lm_with_pc)[1,] + 
                      confint(lm_with_pc)[grepl("center", rownames(confint(lm_with_pc))),] )
llm_coefs <- c( coef(llm_with_pc)[c("dde", "PC1")],
   "center5" = as.numeric(coef(llm_with_pc)[1]),
   coef(llm_with_pc)[1] + coef(llm_with_pc)[ grepl("center", names(coef(llm_with_pc))) ] )
suppressMessages(llm_confint <- rbind(confint(llm_with_pc)[c("dde", "PC1"),],
                    "center5" = confint(llm_with_pc)[1,],
                    confint(llm_with_pc)[1,] + 
                      confint(llm_with_pc)[grepl("center", rownames(confint(llm_with_pc))),] ) )
lm_coefs <- cbind.data.frame(Mean = lm_coefs, lm_confint)
llm_coefs <- cbind.data.frame(Mean = llm_coefs, llm_confint)
```

95\% confidence interval for Gaussian regression:
```{r, echo=F, include=T}
round(lm_coefs[c("dde", "PC1"),], 3)
```

For logistic regression:
```{r, echo=F, include=T}
round(llm_coefs[c("dde", "PC1"),], 3)
```

  * Hard to see improvement from a "baseline" model (Gaussian)

## Diagnostic Plots

```{r, echo=F, include=T}
par(mfrow = c(1, 2))
plot(lm_with_pc, 1, main = "Gaussian regression")
binnedplot(fitted(llm_with_pc),
           residuals(llm_with_pc, type = "response"),
           xlab = "Fitted response",
           ylab = "Residual",
           main = "Logistic regression (43 bins)")
```

```{r}
load("./HP_pcb.rdata")
quant5 = function(x) {round(quantile(x, c(0.025, 0.5, 0.975)),2)} ## 95% CI
pcb = dplyr::select(data.frame(beta.sim),starts_with("pcb_"))
pcb_fit<- cbind(lwr= apply(pcb, 2, quant5)[1,], fit= apply(pcb, 2, quant5)[2,], upr=apply(pcb, 2, quant5)[3,])

ggplot(as.data.frame(pcb_fit), aes(rownames(pcb_fit), 
  fit, size=10, group=1, ylim=max(upr)+0.8)) +
  theme_bw(base_size=10)+ 
  geom_point(size=2)+
  geom_line(size=1)+
  geom_errorbar(aes(ymin = lwr, ymax = upr), width = 0.2, size=1)+
  xlab("Lab")+
  ylab("Fitted value")+
  ggtitle("Gestational Age acorss (JAGS)")+
  theme(axis.text.x=element_blank())+
  geom_text(aes(label = round(lwr,2), y = lwr), vjust = 1.5, size=3) +
  geom_text(aes(label = round(upr,2), y = upr), vjust = -0.5, size=3) +
  geom_text(aes(label = rownames(pcb_fit), y = upr+0.5), vjust = -0.5, size=3, col="blue")
```


## Result

## Conclusion
